version: "3.9"
services:
  hugging-face-course:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - course-data:/app/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  course-data:
